- hosts: localhost
  tasks:
    - name: Launch an EC2 instance
      ec2:
        key_name: my-key
        instance_type: t2.micro
        image: ami-0c55b159cbfafe1f0
        region: us-east-1
        wait: yes
